### ISSUE TITLE
python dynamic test registration: potential to fail to register unique tests

### ISSUE THREAD

**Issue by namedots** [codewars/docs#266] opened 2021-02-12 11:18 UTC
I was asked by hobovsky to describe this situation -

There's an example [here](https://docs.codewars.com/languages/python/authoring/#dynamically-generated-test-cases):

```python
@test.describe("Generated test cases")
def tests_with_generated_test_cases()
    test_cases = generate_test_cases()
    for msg, input, expected in test_case:
        @test.it(msg)
        def _():
            actual = user_solution(input)
            test.assert_equals(actual, expected)
```

which has a potential bug in it - the test framework could decide to call `_` after the loop has finished
what this will do is that all instances of `_` will have the same value for `input` and `expected` as those are variables existing in the surrounding scope and python closures do not capture current values but instead the variables themselves

as a small demonstration:

```python
funs = []

# register 0 1 2 3
for i in range(4):
    def f():
        print(i)
    funs.append(f)

for f in funs:
    f()  # expected 0 1 2 3
         # but prints 3 3 3 3
```

this pattern is totally fine with the current test framework which immediately calls the registered function and maybe it's reasonable. still, the potential is there and this does happen in javascript - node 8.something calls the functions immediately, while a more recent version holds on to the callbacks to be invoked later (and javascript has the same capturing behaviour for closures) sorry I don't have reproducing code for that, so that part is anecdotal evidence

Personally, I've been doing this:

```python
def check(indata, expected):
    reel, spin = indata
    test.it(f"fruit({reel!r}, {spin!r})")(
        lambda: test.assert_equals(fruit(reel, spin), expected)
    )

# ...

for indata, expected in test_cases:
    check(indata, expected)
```

no clue what other people think of that but it gets around the problem since it immediately binds the test parameters

**Comment by kazk** [comment] 2021-02-12 11:35
> the test framework could decide to call `_` after the loop has finished

This won't happen because it's a huge breaking change. This will completely changes the test framework. I'd rather throw it away and use a proper test framework :P

> (and javascript has the same capturing behaviour for closures)

JavaScript have block scope (`let`/`const`) (or you can also use IIFE):

```javascript
// All of these will work
{
  const funs = [];
  for (let i = 0; i < 5; ++i) funs.push(() => i);
  funs.forEach(f => console.log(f()));
}
{
  const funs = [];
  for (const i of [0,1,2,3,4]) funs.push(() => i);
  funs.forEach(f => console.log(f()));
}
{ // If you "really" need "var" for some strange reason, use IIFE
  const funs = [];
  for (var i = 0; i < 5; ++i) funs.push(((i) => () => i)(i));
  funs.forEach(f => console.log(f()));
}
```

**Comment by kazk** [comment] 2021-02-12 11:51
> node 8.something calls the functions immediately, while a more recent version holds on to the callbacks to be invoked later

This is because I threw away the custom test framework. My mistake was trying to make Node 10 somewhat compatible implicitly. Node 12 makes it more clear that it's a different test framework.

I won't repeat Node 10 mistake again, so you can assume the change you're worried about won't happen.

**Comment by hobovsky** [comment] 2021-02-12 11:57
Sorry guys but it seems I've done a mistake of either putting the mentioned points in the tutorial, _or_ escalating this issue here, I just do not know which exactly :)

Just please tell me explicitly whether JS and Python tutorials are wrong and need to be fixed in some way, or they are OK as they are and the approach they describe is correct? Is there anything to remove/fix/update there? Or maybe the problem is that "it works", but it's not how things should be done?

Sorry, but I am a total noob when it comes to both Python and JS :(

**Comment by kazk** [comment] 2021-02-12 12:01
Python: It's fine. The test framework won't change to cause a problem.

JavaScript: Mocha doesn't run the function immediately, so it's possible to have the issue described. There's really no reason to use `var` in JS anymore (`let`/`var` used to be much slower many years ago), so always use block scope (`let`/`const`).

**Comment by namedots** [comment] 2021-02-12 12:01
I saw casual mention of making use of `describe`/`it` because that would be compatible with real test frameworks, and writing this code would then be a bit shady but uh I know absolutely nothing ^^

A function itself implies that it can be called later, that's enough to bother me, and decorators invite writing that pattern. But it's kind of a nitpick and not even directed at the docs - seems reasonable to me as it is.

**Comment by kazk** [comment] 2021-02-12 12:09
Just to be clear, I don't think anyone likes the test framework. I don't. The decorator was a smart way to make it much better without breaking existing contents. Before that, you had to call `print("<COMPLETEDIN::>")` :man_facepalming:

> that would be compatible with real test frameworks

Don't take that too literally. I probably said something like "more" compatible, but I just meant it'll at least force some structure. Some tests are just terrible and using `describe`/`it` should at least make it more understandable and thus maintainable.

**Comment by kazk** [comment] 2021-02-12 12:17
JS tutorial is using `forEach` and `let` so it's fine, but probably worth highlighting. I'd recommend using `const` whenever possible and `let` when necessary, and never `var`.

**Comment by hobovsky** [comment] 2021-02-12 12:25
For JS, I will check if Mocha has some proper mechanism for creating generated test cases.

The way how it's described now just mimics Python approach which suited also the old JS testing framework, but since Mocha is a full-fledged testing framework, maybe it provides some better mechanisms. I will check its docs and update the tutorial.

**Comment by kazk** [comment] 2021-02-12 12:35
For Python, it's probably worth mentioning that the decorated function is executed immediately if it's not already. I think most of us are too used to it and have forgotten how weird it is. It's definitely not obvious.

@namedots, thanks for bringing it up.

**Comment by kazk** [comment] 2021-02-12 12:41
By the way, Mocha doesn't have it built-in. I honestly don't think it makes much sense in Mocha to have this feature when you can generate however you want. See https://mochajs.org/#dynamically-generating-tests

There are many test framework-agnostic packages for testing. If find anything, feel free to make requests.

**Comment by hobovsky** [comment] 2021-02-12 12:53
Oh that's cool, so you generally get generated test cases for free and do not need to do any boilerplate like creating a generator, binding it to a test function, blah blah blah. That's nice.

**Comment by hobovsky** [comment] 2021-02-18 16:22
I've created https://github.com/codewars/docs/pull/268 to add suggested notes, but I am totally not sure if they are OK. Please take a look and let me know or suggest improvements.

**Closed** 2021-02-20 10:03 UTC
